### ISSUE TITLE
Bugs List by Nguyễn Viết Bảo Huy

### ISSUE THREAD

**Issue by GniK189** [NguyenPhanTrungHieu/PTrinhBacNhat2An#1]
[BugsList_NguyenVietBaoHuy.xlsx](https://github.com/NguyenPhanTrungHieu/PTrinhBacNhat2An/files/14418189/BugsList_NguyenVietBaoHuy.xlsx)

**Comment by NguyenPhanTrungHieu** [comment]
Đã Sửa
